import { IType } from "@/interfaces";
import TypeModel from "../models/type.model";

const types: IType[] = [
    // roles
    {
        title: 'Monthly',
        cat: 'Membership',
        subCat: '550',
        description: '',
        isActive: true,
    },
    {
        title: 'ADMIN',
        cat: 'Role',
        subCat: 'ADMIN',
        description: '',
        isActive: true,
    },
    {
        title: 'USER',
        cat: 'Role',
        subCat: 'USER',
        description: '',
        isActive: true,
    },
    // address
    {
        title: 'HOME',
        cat: 'Address',
        subCat: 'HOME',
        description: '',
        isActive: true,
    },

    {
        title: 'OFFICE',
        cat: 'Address',
        subCat: 'OFFICE',
        description: '',
        isActive: true,
    },
    {
        title: 'OTHER',
        cat: 'Address',
        subCat: 'OTHER',
        description: '',
        isActive: true,
    },
    // gender
    {
        title: 'Male',
        cat: 'Gender',
        subCat: 'Male',
        description: '',
        isActive: true,
    },
    {
        title: 'Female',
        cat: 'Gender',
        subCat: 'Female',
        description: '',
        isActive: true,
    },
    // blog type
    {
        title: 'Simple Squad',
        cat: 'Blog',
        subCat: 'Leg',
        subSubCat: 'Squad',
        description: '',
        isActive: true,
    },
    {
        title: 'Weighted Squad',
        cat: 'Blog',
        subCat: 'Leg',
        subSubCat: 'Squad',
        description: '',
        isActive: true,
    },
    {
        title: 'Chest Press',
        cat: 'Blog',
        subCat: 'Chest',
        subSubCat: 'Chest',
        description: '',
        isActive: true,
    },
    {
        title: 'Incline Chest Press',
        cat: 'Blog',
        subCat: 'Chest',
        subSubCat: 'Chest',
        description: '',
        isActive: true,
    },
    {
        title: 'Decline Chest Press',
        cat: 'Blog',
        subCat: 'Chest',
        subSubCat: 'Chest',
        description: '',
        isActive: true,
    },
    {
        title: 'Shoulder Press',
        cat: 'Blog',
        subCat: 'Shoulder',
        subSubCat: 'Shoulder',
        description: '',
        isActive: true,
    },
    {
        title: 'Lateral Raise',
        cat: 'Blog',
        subCat: 'Shoulder',
        subSubCat: 'Lateral',
        description: '',
        isActive: true,
    },
    {
        title: 'Front Raise',
        cat: 'Blog',
        subCat: 'Shoulder',
        subSubCat: 'Front',
        description: '',
        isActive: true,
    },
    {
        title: 'Bicep Curl',
        cat: 'Blog',
        subCat: 'Arm',
        subSubCat: 'Bicep',
        description: '',
        isActive: true,
    },
    {
        title: 'Tricep Extension',
        cat: 'Blog',
        subCat: 'Arm',
        subSubCat: 'Tricep',
        description: '',
        isActive: true,
    },
    {
        title: 'Tricep Dips',
        cat: 'Blog',
        subCat: 'Arm',
        subSubCat: 'Tricep',
        description: '',
        isActive: true,
    },
    {
        title: 'Lunges',
        cat: 'Blog',
        subCat: 'Leg',
        subSubCat: 'thigh',
        description: '',
        isActive: true,
    },
    {
        title: 'Deadlifts',
        cat: 'Blog',
        subCat: 'Leg',
        subSubCat: 'Leg',
        description: '',
        isActive: true,
    },
    {
        title: 'Leg Press',
        cat: 'Blog',
        subCat: 'Leg',
        subSubCat: 'Leg',
        description: '',
        isActive: true,
    },
    {
        title: 'Plank',
        cat: 'Blog',
        subCat: 'Core',
        subSubCat: 'Core',
        description: '',
        isActive: true,
    },
    {
        title: 'Crunches',
        cat: 'Blog',
        subCat: 'Core',
        subSubCat: 'Core',
        description: '',
        isActive: true,
    },
    {
        title: 'Russian Twists',
        cat: 'Blog',
        subCat: 'Core',
        subSubCat: 'Core',
        description: '',
        isActive: true,
    },


    // documentTypes
    {
        title: 'logo',
        cat: 'Document',
        subCat: 'icon',
        description: '',
        isActive: true,
    },
    {
        title: 'cover',
        cat: 'Document',
        subCat: 'photo',
        description: '',
        isActive: true,
    },
    // organisationTypes
    {
        title: 'GOVERNMENT',
        cat: 'Organisation',
        subCat: 'GOVERNMENT',
        description: '',
        isActive: true,
    },
    {
        title: 'PRIVATE',
        cat: 'Organisation',
        subCat: 'PRIVATE',
        description: '',
        isActive: true,
    },
    {
        title: 'NGO',
        cat: 'Organisation',
        subCat: 'NGO',
        description: '',
        isActive: true,
    },
    {
        title: 'TRUST',
        cat: 'Organisation',
        subCat: 'TRUST',
        description: '',
        isActive: true,
    },
    {
        title: 'SOCIETY',
        cat: 'Organisation',
        subCat: 'SOCIETY',
        description: '',
        isActive: true,
    },
    {
        title: 'CLUB',
        cat: 'Organisation',
        subCat: 'CLUB',
        description: '',
        isActive: true,
    },
    {
        title: 'ASSOCIATION',
        cat: 'Organisation',
        subCat: 'ASSOCIATION',
        description: '',
        isActive: true,
    },
    {
        title: 'FIRM',
        cat: 'Organisation',
        subCat: 'FIRM',
        description: '',
        isActive: true,
    },
    {
        title: 'COMPANY',
        cat: 'Organisation',
        subCat: 'COMPANY',
        description: '',
        isActive: true,
    },
    {
        title: 'PARTNERSHIP',
        cat: 'Organisation',
        subCat: 'PARTNERSHIP',
        description: '',
        isActive: true,
    },
    {
        title: 'SOLEPROPRIETORSHIP',
        cat: 'Organisation',
        subCat: 'SOLEPROPRIETORSHIP',
        description: '',
        isActive: true,
    },
    {
        title: 'COOPERATIVE',
        cat: 'Organisation',
        subCat: 'COOPERATIVE',
        description: '',
        isActive: true,
    },

    // contactTypes
    {
        title: 'MOBILE',
        cat: 'Contact',
        subCat: 'MOBILE',
        subSubCat: 'PHONE',
        description: '',
        isActive: true,
    },
    {
        title: 'MOBILE',
        cat: 'Contact',
        subCat: 'MOBILE',
        subSubCat: 'WHATSAPP',
        description: '',
        isActive: true,
    },
    {
        title: 'MOBILE',
        cat: 'Contact',
        subCat: 'MOBILE',
        subSubCat: 'ALL',
        description: '',
        isActive: true,
    },
    {
        title: 'MOBILE',
        cat: 'Contact',
        subCat: 'MOBILE',
        subSubCat: 'ALTERNATE',
        description: '',
        isActive: true,
    },
    {
        title: 'EMAIL',
        cat: 'Contact',
        subCat: 'EMAIL',
        description: '',
        isActive: true,
    },
    {
        title: 'WEBSITE',
        cat: 'Contact',
        subCat: 'WEBSITE',
        description: '',
        isActive: true,
    },
    {
        title: 'FACEBOOK',
        cat: 'Contact',
        subCat: 'FACEBOOK',
        description: '',
        isActive: true,
    },
    {
        title: 'TWITTER',
        cat: 'Contact',
        subCat: 'TWITTER',
        description: '',
        isActive: true,
    },
    {
        title: 'LINKEDIN',
        cat: 'Contact',
        subCat: 'LINKEDIN',
        description: '',
        isActive: true,
    },
    {
        title: 'INSTAGRAM',
        cat: 'Contact',
        subCat: 'INSTAGRAM',
        description: '',
        isActive: true,
    },
    {
        title: 'TELEGRAM',
        cat: 'Contact',
        subCat: 'TELEGRAM',
        description: '',
        isActive: true,
    },
    {
        title: 'YOUTUBE',
        cat: 'Contact',
        subCat: 'YOUTUBE',
        description: '',
        isActive: true,
    },
    // tags
    {
        title: 'UPSE',
        cat: 'Tag',
        subCat: 'UPSE',
        description: '',
        isActive: true,
    },
    {
        title: 'SSC',
        cat: 'Tag',
        subCat: 'SSC',
        description: '',
        isActive: true,
    },
    {
        title: 'BANK',
        cat: 'Tag',
        subCat: 'BANK',
        description: '',
        isActive: true,
    },
    {
        title: 'RAILWAY',
        cat: 'Tag',
        subCat: 'RAILWAY',
        description: '',
        isActive: true,
    },
    {
        title: 'DEFENCE',
        cat: 'Tag',
        subCat: 'DEFENCE',
        description: '',
        isActive: true,
    },
    {
        title: 'POLICE',
        cat: 'Tag',
        subCat: 'POLICE',
        description: '',
        isActive: true,
    },
    {
        title: 'TEACHER',
        cat: 'Tag',
        subCat: 'TEACHER',
        description: '',
        isActive: true,
    },
    {
        title: 'ENGINEER',
        cat: 'Tag',
        subCat: 'ENGINEER',
        description: '',
        isActive: true,
    },
    {
        title: 'DOCTOR',
        cat: 'Tag',
        subCat: 'DOCTOR',
        description: '',
        isActive: true,
    },
    {
        title: 'LAWYER',
        cat: 'Tag',
        subCat: 'LAWYER',
        description: '',
        isActive: true,
    },
    {
        title: 'ACCOUNTANT',
        cat: 'Tag',
        subCat: 'ACCOUNTANT',
        description: '',
        isActive: true,
    },
    {
        title: 'ARCHITECT',
        cat: 'Tag',
        subCat: 'ARCHITECT',
        description: '',
        isActive: true,
    },
    {
        title: 'FARMER',
        cat: 'Tag',
        subCat: 'FARMER',
        description: '',
        isActive: true,
    },
    {
        title: 'STUDENT',
        cat: 'Tag',
        subCat: 'STUDENT',
        description: '',
        isActive: true,
    },
    {
        title: 'BUSINESSMAN',
        cat: 'Tag',
        subCat: 'BUSINESSMAN',
        description: '',
        isActive: true,
    }
]

export const typeSeed = async (): Promise<IType[]> => {
    const model = await TypeModel.insertMany(types);
    return model;
}
